### ISSUE TITLE
Unit tests failing

### ISSUE THREAD

**Issue by mattdodge** [nio-blocks/google_oauth#29]
Among others, this is a failure:
```
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/nio_blocks/nio_blocks/google_oauth/tests/test_google_oauth.py", line 86, in test_addl_params
    "prop_value": "value2"
  File "/var/lib/jenkins/jobs/nio/workspace/src/nio/util/support/block_test_case.py", line 100, in configure_block
    ''))
  File "/var/lib/jenkins/jobs/nio_blocks/nio_blocks/google_oauth/http_blocks/rest/rest_block.py", line 61, in configure
    self._authenticate()
  File "/var/lib/jenkins/jobs/nio_blocks/nio_blocks/google_oauth/google_oauth_block.py", line 76, in _authenticate
    scope=self.get_google_scope())
  File "/var/lib/jenkins/jobs/nio_blocks/nio_blocks/google_oauth/oauth2_mixin/oauth2_service.py", line 28, in get_access_token
    key_info = self._load_json_file(self.key_config_file)
  File "/var/lib/jenkins/jobs/nio_blocks/nio_blocks/google_oauth/oauth2_mixin/oauth2_base.py", line 98, in _load_json_file
    self.key_config_file))
nio_blocks.google_oauth.oauth2_mixin.oauth2_base.OAuth2Exception: Could not find key file etc/private_key.json. Should be an absolute path or relative to the current environment.
```

**Comment by hansmosh** [comment]
This was fixed by PR #30
